### ISSUE TITLE
A bug & the hacky, quick fix: nsIWebBrowserPersist.saveURI() throws an exception with Gecko 36

### ISSUE THREAD

**Issue by lembitk** [dafizilla/firefox-viewsourcewith#2] opened 2015-02-26 23:33 UTC
After updating my Firefox to v36.0 recently, the ViewSourceWith extension v0.9.4.2 stopped working (I'm on Win7 x64). When trying to view source, either via shortcut or menus, got the following error message: 

> viewPage: [Exception... "Not enough arguments [nsIWebBrowserPersist.saveURI]"  nsresult: "0x80570001 (NS_ERROR_XPC_NOT_ENOUGH_ARGS)"  location: "JS frame :: chrome://viewsourcewith/content/urldownloader.js :: ViewSourceWithUrlDownloader.prototype.internalSaveURI :: line 134"  data: no]

It seems the problem is in that Gecko v36.0 has introduced a new parameter for the ```nsIWebBrowserPersist.saveURI()``` method, ```aReferrerPolicy``` – please [refer to the docs at MDN](https://developer.mozilla.org/en-US/docs/Mozilla/Tech/XPCOM/Reference/Interface/nsIWebBrowserPersist#saveURI()). 

Considering the MDN docs, I unpacked the 'viewsourcewith.jar' file and located the [line 134](https://github.com/dafizilla/firefox-viewsourcewith/blob/master/src/main/content/viewsourcewith/urldownloader.js#L134) in 'content/viewsourcewith/urldownloader.js': 

```javascript
persist.saveURI(uri, null, referrer, postData, null, outFile, privacyContext);
```

I replaced it with the following: 

```javascript
persist.saveURI(uri, null, referrer, null, postData, null, outFile, privacyContext);
```

I.e. giving the newly introduced parameter ```aReferrerPolicy``` value of ```null```. 

After repackaging the extension with the patched 'urldownloader.js', ViewSourceWith works in my Firefox v36.0 as expected again.

I hope that this information might help you in patching and updating the extension. Thank you for your attention, and thank you for developing such a useful, valuable extension – I've been using it constantly in my daily work for a long time.

**Comment by sun** [comment] 2015-02-28 11:18
This compatibility problem has been fixed in the newly released v0.9.4.3 already.

However, in my case, Firefox did not automatically update the add-on.  The [add-on page](https://addons.mozilla.org/en-us/firefox/addon/dafizilla-viewsourcewith/) exposes a manual download button, which guides to a [roadblock page](https://addons.mozilla.org/en-us/firefox/addon/dafizilla-viewsourcewith/contribute/roadblock/?src=dp-btn-primary&version=0.9.4.3), asking users for contributions.

Legitimate request.  I donated and updated.  The new version works correctly.

Thanks, @dafi!

**Comment by dafi** [comment] 2015-02-28 11:21
Please apologize for annoying donation request, these pages are out of my control, they are handled by Mozilla.

BTW thanks to support VSW

**Comment by lembitk** [comment] 2015-02-28 21:39
Thanks @dafi for fixing this promptly with 6bd5a6b. In my case, Firefox has done the automatic update to v0.9.4.3 today and VSW continues to work as expected.

**Closed** 2015-03-20 14:39 UTC

**Comment by lembitk** [comment] 2015-06-17 23:04
Hello @dafi. After updating my Thunderbird to v38.0.1 recently, the exact same error occurs there with the older ViewSourceWith add-on v0.9.4.2. Which is of course expected, and I also do know that most probably I could get the add-on working again by [manually updating it to v0.9.4.3.1-signed](https://addons.mozilla.org/en-us/firefox/addon/dafizilla-viewsourcewith/contribute/roadblock/). So, I'm writing this to let you know that I cannot update the add-on via TBird's Add-ons Manager. I'm not sure if you even can do something about it, but if you can, it would surely be highly appreciated, as I would guess I'm not alone in facing this tiny issue… Thanks.

**Comment by dafi** [comment] 2015-06-18 15:47
Hi, I could re-add compatibility with TB but I no longer use it, so users could download a totally untested and bugged version. If the specific TB code (calling Mozilla API) used in VSW has been changed the user experience can be very frustrating

**Comment by lembitk** [comment] 2015-06-18 16:23
Oh, I see… Are you saying that you don't support TB within VSW anymore? And as such, manually updating to v0.9.4.3.1-signed would probably be a bad idea?

**Comment by dafi** [comment] 2015-06-20 09:18
I can't support TB because I don't use it, I prefer to release code I test.
You are free to manually sign VSW to continue to use it with TB.
If you find a bug on TB I will fix it but I will be very slow to fix it because I must install TB, create a test env and finally reproduce the problem inside an application I no longer use

**Comment by lembitk** [comment] 2015-06-20 20:52
Thanks @dafi, I completely understand. While your add-on has been very convenient and valuable for me within TB, I feel I don't want to hack it manually nor bug you with TB-specific bugs. Will use the built-in source viewer for the time being instead. 

Thanks again, :bow:.

PS. Maybe you could update the [add-on description at the Mozilla Add-on directory](https://addons.mozilla.org/en-US/firefox/addon/dafizilla-viewsourcewith/) sometime (the portion starting “Thunderbird users can…”), so folks won't try to use it with TB in vain.

**Comment by dafi** [comment] 2015-06-21 09:49
You are right, removed the description portion on AMO site
